#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.datasource.url=jdbc:h2:~/test;
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/beer_community?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: false
                format_sql: true
                default_batch_fetch_size: 100
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
    level:
        org.hibernate.SQL: debug


#spring:
#    datasource:
#        url: jdbc:h2:tcp://localhost/~/test
#        username: sa
#        password:
#        driver-class-name: org.h2.Driver
#
#    jpa:
#        hibernate:
#            ddl-auto: create
#        properties:
#            hibernate:
#                # show_sql: true
#                format_sql: true
#    data:
#        web:
#            pageable:
#                default-page-size: 10
#                max-page-size: 2000
#
#logging.level:
#org.hibernate.SQL: debug
## org.hibernate.type: trace